# 使用node镜像作为基础镜像来构建Vue项目
FROM node:18-alpine AS build-stage

# 设置工作目录
WORKDIR /app

# 将项目文件复制到容器中
COPY . .

# 安装依赖
RUN npm install

# 构建项目
RUN npm run build

# 使用Nginx作为生产阶段的基础镜像
FROM nginx:1.21-alpine AS production-stage

# 拷贝打包好的文件到Nginx的默认目录
COPY --from=build-stage /app/dist /usr/share/nginx/html

# 暴露Nginx的默认端口
EXPOSE 80

# 启动Nginx
CMD ["nginx", "-g", "daemon off;"]
